CA-234494: update startup cleanup&generation script
Use control domain to detect the presence of the new
is-default-template filed and use the information to call the
appropriate cleanup function.

Signed-off-by: Marcello Seri <marcello.seri@citrix.com>

diff --git a/62-create-guest-templates b/62-create-guest-templates
--- a/62-create-guest-templates
+++ b/62-create-guest-templates
@@ -14,6 +14,17 @@ this_host_is_master(){
     return $?
 }
 
+# Return zero if xapi VMs have the is-default-template field and non-zero otherwise.
+check_has_default_template_field() {
+    # disable set -e option saving current options state, then reinstate it before returning
+    old_set=$-; set +e
+    ctrl_domain=$(xe vm-list is-control-domain=true --minimal)
+    $XE vm-param-list uuid=$ctrl_domain | grep -q is-default-template
+    has_new_key=$?
+    set -$old_set
+    return $has_new_key
+}
+
 # Remove all default_templates if we have upgraded from a platform version < 2.1.1
 remove_built_in_templates() {
     source /etc/xensource-inventory
@@ -25,10 +36,15 @@ remove_built_in_templates() {
          \( "$major" -eq 2 -a "$minor" -lt 1 \) -o \
          \( "$major" -eq 2 -a "$minor" -eq 1 -a "$sub" -lt 1 \) ]; then
         echo "Removing all default templates"
+        has_default_template_field=check_has_default_template_field
         IFS=","; for uuid in $($XE template-list other-config:default_template=true --minimal); do
-	    echo "Removing old template: $($XE template-list uuid=$uuid params=name-label --minimal)"
-	    $XE vm-param-set uuid=$uuid is-a-template=false other-config:default_template=false
-	    $XE vm-destroy uuid=$uuid
+        echo "Removing old template: $($XE template-list uuid=$uuid params=name-label --minimal)"
+        if $has_default_template_field; then
+            $XE vm-param-set uuid=$uuid is-default-template=false is-a-template=false
+        else
+            $XE vm-param-set uuid=$uuid is-a-template=false other-config:default_template=false
+        fi
+        $XE vm-destroy uuid=$uuid
         done
     fi
 }
@@ -37,13 +53,13 @@ start() {
     XAPI_START_TIMEOUT_SECONDS=240
 
     if this_host_is_master; then
-	if /opt/xensource/bin/xapi-wait-init-complete ${XAPI_START_TIMEOUT_SECONDS}; then
-	    remove_built_in_templates
-	    create-guest-templates
-	    return 0
-	else
-	    return 1
-	fi
+        if /opt/xensource/bin/xapi-wait-init-complete ${XAPI_START_TIMEOUT_SECONDS}; then
+            remove_built_in_templates
+            create-guest-templates
+            return 0
+        else
+            return 1
+        fi
     fi
 }
 
